# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Fetch person counts

on:
  schedule: 
    - cron: '*/20 0-13 * * 1-6'
    - cron: '*/20 0-8 * * 0'
    #     - cron: '*/20 1-13 * * 6'
    # - cron: '*/15 * * * *'  # Mon. - Fri., run every 5 minutes (during 6-22)  0/5 6-22 * * 1-5
    # - cron: '0/5 * * * *'  # Sat. & Sun., run every 5 minutes (during 9-22)  0/5 9-22 * * 6,0
  push:
    branches:
      - main

jobs:
  build:
    if: "!contains(github.event.commits[0].message, '[skip ci]')"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10']

    steps:
    - uses: actions/checkout@v2
    - name: Save data
      run: |
        wget -O docs/counts.tsv https://yongfu.name/ntu-gym/counts.tsv
        cat docs/counts.tsv
        sudo timedatectl set-timezone Asia/Taipei
        python main.py
        # date +%s > ./docs/version.txt
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs
        enable_jekyll: false
