# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Update Corpus Data

on: 
  push:
  repository_dispatch:
  schedule:
    - cron: '5 * * * *'

jobs:
  build:
    if: "!contains(github.event.commits[0].message, '[skip ci]')"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10']

    steps:
    - uses: actions/checkout@v2
    - name: Build data
      run: |
        wget -O docs/counts.tsv https://yongfu.name/ntu-gym/counts.tsv
        cat docs/counts.tsv
        sudo timedatectl set-timezone Asia/Taipei
        # date +%s > ./docs/version.txt
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs
        enable_jekyll: false
